/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#005bc4',
        'primary-container': '#4388fd',
        'primary-dim': '#004fad',
        secondary: '#006d4a',
        'secondary-container': '#6ffbbe',
        'secondary-dim': '#005f40',
        tertiary: '#bd0c3b',
        'tertiary-container': '#fc4563',
        'tertiary-fixed-dim': '#ea3858',
        surface: '#f7f9fb',
        'surface-bright': '#f7f9fb',
        'surface-dim': '#d4dbdf',
        'surface-container': '#eaeff2',
        'surface-container-low': '#f0f4f7',
        'surface-container-high': '#e3e9ed',
        'surface-container-highest': '#dce4e8',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#2c3437',
        'on-surface-variant': '#596064',
        'on-primary': '#f9f8ff',
        'on-secondary': '#e6ffee',
        'on-tertiary': '#fff7f6',
        'on-primary-container': '#000311',
        'on-secondary-container': '#005e3f',
        outline: '#747c80',
        'outline-variant': '#acb3b7',
        error: '#a83836',
        'error-container': '#fa746f',
        'on-error': '#fff7f6',
        background: '#f7f9fb',
        'on-background': '#2c3437',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
        '5xl': '2.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
