/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary:                    'rgb(var(--color-primary) / <alpha-value>)',
        'primary-container':        'rgb(var(--color-primary-container) / <alpha-value>)',
        'primary-dim':              'rgb(var(--color-primary-dim) / <alpha-value>)',
        secondary:                  'rgb(var(--color-secondary) / <alpha-value>)',
        'secondary-container':      'rgb(var(--color-secondary-container) / <alpha-value>)',
        'secondary-dim':            'rgb(var(--color-secondary-dim) / <alpha-value>)',
        tertiary:                   'rgb(var(--color-tertiary) / <alpha-value>)',
        'tertiary-container':       'rgb(var(--color-tertiary-container) / <alpha-value>)',
        'tertiary-fixed-dim':       'rgb(var(--color-tertiary-fixed-dim) / <alpha-value>)',
        surface:                    'rgb(var(--color-surface) / <alpha-value>)',
        'surface-bright':           'rgb(var(--color-surface-bright) / <alpha-value>)',
        'surface-dim':              'rgb(var(--color-surface-dim) / <alpha-value>)',
        'surface-container':        'rgb(var(--color-surface-container) / <alpha-value>)',
        'surface-container-low':    'rgb(var(--color-surface-container-low) / <alpha-value>)',
        'surface-container-high':   'rgb(var(--color-surface-container-high) / <alpha-value>)',
        'surface-container-highest':'rgb(var(--color-surface-container-highest) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--color-surface-container-lowest) / <alpha-value>)',
        'on-surface':               'rgb(var(--color-on-surface) / <alpha-value>)',
        'on-surface-variant':       'rgb(var(--color-on-surface-variant) / <alpha-value>)',
        'on-primary':               'rgb(var(--color-on-primary) / <alpha-value>)',
        'on-secondary':             'rgb(var(--color-on-secondary) / <alpha-value>)',
        'on-tertiary':              'rgb(var(--color-on-tertiary) / <alpha-value>)',
        'on-primary-container':     'rgb(var(--color-on-primary-container) / <alpha-value>)',
        'on-secondary-container':   'rgb(var(--color-on-secondary-container) / <alpha-value>)',
        outline:                    'rgb(var(--color-outline) / <alpha-value>)',
        'outline-variant':          'rgb(var(--color-outline-variant) / <alpha-value>)',
        error:                      'rgb(var(--color-error) / <alpha-value>)',
        'error-container':          'rgb(var(--color-error-container) / <alpha-value>)',
        'on-error':                 'rgb(var(--color-on-error) / <alpha-value>)',
        background:                 'rgb(var(--color-background) / <alpha-value>)',
        'on-background':            'rgb(var(--color-on-background) / <alpha-value>)',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body:     ['Manrope', 'sans-serif'],
        label:    ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:   '0.5rem',
        xl:   '0.75rem',
        '2xl':'1rem',
        '3xl':'1.5rem',
        '4xl':'2rem',
        '5xl':'2.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
